Repository sodafoundation/strato, pull requests merged in 2021-06, with the labels that each got.

#1269 CRUD API for tiering
  api/pkg/backend/router.go
  api/pkg/backend/service.go
  backend/pkg/db/db.go
  backend/pkg/db/drivers/mongo/mongo.go
  backend/pkg/model/model.go
  backend/pkg/service/service.go
  backend/pkg/service/service_test.go
  backend/proto/backend.pb.go
  backend/proto/backend.pb.micro.go
  backend/proto/backend.proto
  block/pkg/utils/utils_test.go
  testutils/backend/db/testing/repository.go
  testutils/backend/proto/backend_service.go
Labels: High Priority, feature

#1271 Bucket creation using tier
  api/pkg/s3/bucketput.go
  api/pkg/s3/service.go
Labels: enhancement

#1273 Policy based access for CRUD Tier API
  api/pkg/backend/service.go
  api/pkg/common/common.go
  api/pkg/examples/policy.json
  api/pkg/s3/bucketput.go
  api/pkg/s3/objectput.go
  api/pkg/s3/objectrestore.go
  api/pkg/s3/service.go
  api/pkg/utils/utils.go
  backend/pkg/db/db.go
  backend/pkg/db/drivers/mongo/mongo.go
  backend/pkg/model/model.go
  backend/pkg/service/service.go
  backend/proto/backend.pb.go
  backend/proto/backend.proto
  s3/pkg/conf/tidb.sql
  s3/pkg/meta/db/drivers/tidb/bucket.go
  s3/pkg/meta/types/bucket.go
  s3/pkg/service/bucket.go
  s3/pkg/service/object.go
  s3/pkg/utils/utils.go
  s3/proto/s3.pb.go
  s3/proto/s3.pb.micro.go
  s3/proto/s3.proto
  testutils/backend/db/testing/repository.go
Labels: feature
